### ISSUE TITLE
Ape tests failing due to "invalid opcode 0x5f" [APE-942]

### ISSUE THREAD

**Issue by derekpierre** [ApeWorX/ape-solidity#100]
### Environment information

- `ape` and plugin versions:

```
$ ape --version
0.6.8

$ ape plugins list
Installed Plugins:
  solidity    0.6.3
```

- Python Version: 3.8
- OS: macOS

### What went wrong?

Running into the following issues running tests for our project that uses ape. The ape config file specifies solidity version 0.8.17. The test suite was previously passing but is now failing without code changes:

The failures manifest as:
With Invalid opcode 0x5f for a variety of tests
```
/home/runner/work/nucypher-contracts/nucypher-contracts/tests/test_subscription_manager.py:12: in proxy_admin
    return accounts[0].deploy(dependency.ProxyAdmin)
E   ape.exceptions.ContractLogicError: Invalid opcode 0x5f @ 31
```
You can view more error logs here - https://github.com/nucypher/nucypher-contracts/pull/80/checks

Please include information like:

- what command you ran
`$ ape test`

- the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)

  https://github.com/nucypher/nucypher-contracts/

- full output of the error you received

  https://github.com/nucypher/nucypher-contracts/pull/80/checks

### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

Could be the incorrect version of solidity, 0.8.20 being used even though 0.8.17 is specified (?)

From ApeWorX Discord:
```
fubuloubu — Today at 2:02 PM

It's using 0.8.20 by accident. What is your config file saying? We might have a bug if you're pinning a specific version and it is not recognizing it

derek — Today at 2:02 PM
solidity:
  version: 0.8.17
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.1"
    - "@openzeppelin-upgradeable/contracts=openzeppelin-upgradeable/v4.8.1"
    
fubuloubu — Today at 2:03 PM
Yup, that's a bug then, it should be pinning to the specific version you state. Can you open an issue in ape-solidity and we can get that fixed?
```

**Comment by derekpierre** [comment]
Any chance this is related to the OpenZeppelin `ProxyAdmin` contract? I've gotten the rest of my test suite to pass, except for my tests that try to use the `ProxyAdmin` contract. OZ v4.8.1 being used. See https://github.com/nucypher/nucypher-contracts/pull/81.

**Comment by derekpierre** [comment]
Looks like one version of solidity is used for compiling contracts in the project (in my case `0.8.17`, and then the latest version `0.8.20` is used for compiling dependency contracts...

Ran with -v DEBUG and saw the following:
```
INFO: Compiling 'matic/SubscriptionManager.sol'.
INFO: Compiling 'threshold/IStaking.sol'.
INFO: Compiling 'contracts/SimplePREApplication.sol'.
DEBUG: Compiling using Solidity compiler '0.8.17+commit.8df45f5f'
....
tests/test_subscription_manager.py::test_initial_parameters DEBUG: 'tmpp53lyn3y' is not an 'ApeProject', but attempting to process as one.
INFO: Compiling 'metatx/ERC2771Context.sol'.
INFO: Compiling 'utils/Context.sol'.
INFO: Compiling 'interfaces/IERC1363Receiver.sol'.
...
INFO: Compiling 'token/ERC1155/extensions/IERC1155MetadataURI.sol'.
INFO: Compiling 'governance/extensions/GovernorVotes.sol'.
INFO: Compiling 'crosschain/arbitrum/CrossChainEnabledArbitrumL2.sol'.
INFO: Compiling 'interfaces/IERC3156FlashBorrower.sol'.
INFO: Compiling 'governance/compatibility/GovernorCompatibilityBravo.sol'.
INFO: Compiling 'mocks/ERC721ConsecutiveEnumerableMock.sol'.
DEBUG: Compiling using Solidity compiler '0.8.20+commit.a1b79de6'
```

**Comment by derekpierre** [comment]
Updating versions of `eth-ape`, `ape-solidity`, `eth-tester` and specifying an `evm_version` for the solidity configuration  in the ape-config.yaml resolved this issue.

**Comment by antazoey** [comment]
this issue is fixed by updating yalls nodes and stuff
