### ISSUE TITLE
Plugin does not handle multiple solidity versions

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape-solidity#27]
* Try to compiling the Uniswap project (https://github.com/Uniswap/v2-core)
* Notice this error:
```
Error: Source file requires different compiler version (current compiler is 0.8.12+commit.f00d7308.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> test/ERC20.sol:1:1:
  |
1 | pragma solidity =0.5.16;
```

Looking at code, it seems like we only using in version in the compile call

**Comment by PatrickAlphaC** [comment]
Bump

**Comment by fubuloubu** [comment]
figured this one out, some debug needed further than can push

**Comment by unparalleled-js** [comment]
Can now compile https://github.com/Uniswap/v2-core using https://github.com/ApeWorX/ape-solidity/pull/33
