### ISSUE TITLE
Allow remapping outside of `contracts` folder

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape-solidity#29]
It is sometimes handy to map to contracts that exist outside of the contracts directory like in `./lib/*` or `./interfaces/*`

**Comment by unparalleled-js** [comment]
You can do this by using a local dependency.
All source files have to be in the same directory.
I think the compiler will have problems when source files are outside of the "base path", which is the `contracts/` directory in Ape's case.

So I am not sure this is possible any other way.

**Comment by unparalleled-js** [comment]
Example from integration tests:

https://github.com/ApeWorX/ape/blob/main/tests/integration/cli/projects/with-dependency/ape-config.yaml

Docs:

https://docs.apeworx.io/ape/stable/userguides/config.html#dependencies
(See bottom of section for local dependencies)

**Comment by fubuloubu** [comment]
> You can do this by using a local dependency.

This will work, so basically do like `./lib/depA` as a local dep, and then do the remapping that way.

**Comment by unparalleled-js** [comment]
> This will work, so basically do like `./lib/depA` as a local dep, and then do the remapping that way.

Yeah, exactly!
