### ISSUE TITLE
Support linking libraries

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape-solidity#43]
currently we areskipping bytecode for contracts using linking.
lets properly support it!
<img width="803" alt="Screen Shot 2022-06-01 at 09 07 19" src="https://user-images.githubusercontent.com/19540978/171424241-4ac41de1-86ab-455a-95f5-d194c24e21c7.png">

https://docs.soliditylang.org/en/v0.8.18/using-the-compiler.html#library-linking

**Comment by fubuloubu** [comment]
so you might have to compile twice if a library is in use? once before deploying the library, and once afterwards?
