### ISSUE TITLE
Support `--optimize-runs` flag to allow changing the run during optimization

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape-solidity#67]
### Overview

Currently, there is no way to configure optimization runs in the plugin.
The runs are included in the published package manifest.
Right now they are always defaulted to 200.

### Specification

`ape-config.yaml`:

```yaml
solidity:
  optimize_runs: 200
```

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by unparalleled-js** [comment]
And when we do this, we can refactor the settings a bit so that it uses the key like:

```
"optimizer": {
  "enabled": true,
  "runs": 200,
}
```

I think we may be able to remove certain settings to, like any that are not in the settings key here: https://docs.soliditylang.org/en/latest/using-the-compiler.html

**Comment by unparalleled-js** [comment]
required https://github.com/ApeWorX/ape-solidity/pull/68
