### ISSUE TITLE
Enable usage of `viaIR` compiler flag for compatible solidity versions [APE-840]

### ISSUE THREAD

**Issue by 0xcefa1090d** [ApeWorX/ape-solidity#94]
### Overview

Provide a simple overview of what you wish to see added. Please include:

- What you are trying to do
- Why Ape's current functionality is inadequate to address your goal

As of [v0.8.13](https://github.com/ethereum/solidity/blob/develop/Changelog.md#0813-2022-03-16), the solidity compiler allows code generation through the Yul IR via the `--via-ir` flag. One noticeable benefit of using this flag is handling stack too deep errors. 

Currently, the ape-solidity plugin doesn't have the ability to enable the `--via-ir` flag, and it would be useful to have the option to do so.

### Specification

A simple config file option `via_ir` would be sufficient.

**Comment by antazoey** [comment]
fixed in https://github.com/ApeWorX/ape-solidity/pull/117
